name: hytale-compose
services:
  game-server:
    image: angelofallaria/hytale:latest
    container_name: game-server
    ports:
      - "5520:5520/udp"
    volumes:
      - server-data:/server/data
    environment:
      - TZ=Asia/Manila

volumes:
  server-data:
    name: server-data
