name: docker-compose-01-deploy

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - docker-compose.yml
    - .github/workflows/docker-compose-01-deploy.yml

jobs:
  upload_docker_compose:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Upload compose.yml file
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: docker-compose.yml
          target: /etc/server

  restart_server:
    needs: upload_docker_compose
    uses: ./.github/workflows/restart-server.yml
    secrets: inherit

  deploy_docker_compose:
    needs: restart_server
    runs-on: ubuntu-latest

    steps:
      - name: Deploy compose.yml file
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /etc/server
            docker compose down
            docker compose pull
            docker compose up -d
