name: docker-compose-01-deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Docker Compose
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Upload compose.yml file
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: docker-compose.yml
          target: /etc/server

      - name: Deploy compose.yml file
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /etc/server
            docker compose down
            docker compose pull
            docker compose up -d
