name: docker-compose-00-validate

on:
  workflow_dispatch:
  push:
    paths:
      - compose.yml
      - .github/workflows/docker-compose-00-validate.yml

jobs:
  validate:
    name: Validate Docker Compose
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - name: Validate Docker Compose Config
        run: docker compose config
